services:
  goldfish:
    build: .
    container_name: goldfish
    volumes:
      - .:/app:delegated
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host 
    stdin_open: true
    tty: true
    entrypoint: ["python", "app.py"]